all: false
dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName}}'
force-file-write: true
formatter: gofmt
log-level: info
structname: '{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
template: testify
packages:
  github.com/trashscanner/trashscanner_api/internal/database/sqlc/db:
    interfaces:
      Querier:
        config:
          dir: 'internal/database/mocks'
          filename: 'querier.go'
  github.com/jackc/pgx/v5:
    interfaces:
      Tx:
        config:
          dir: 'internal/store/mocks'
          filename: 'pgx_tx.go'
  github.com/trashscanner/trashscanner_api/internal/store:
    interfaces:
      Store:
        config:
          dir: 'internal/store/mocks'
          filename: 'store.go'
      Connection:
        config:
          dir: 'internal/store/mocks'
          filename: 'connection.go'
  github.com/trashscanner/trashscanner_api/internal/auth:
    interfaces:
      AuthManager:
        config:
          dir: 'internal/auth/mocks'
          filename: 'auth_manager.go'
  github.com/trashscanner/trashscanner_api/internal/filestore:
    interfaces:
      FileStore:
        config:
          dir: 'internal/filestore/mocks'
          filename: 'file_store.go'
  github.com/trashscanner/trashscanner_api/internal/predictor:
    interfaces:
      predictRequester:
        config:
          dir: 'internal/predictor/'
          filename: 'predictor_client_mock.go'
          structname: 'mockPredictRequester'
          pkgname: 'predictor'