// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/trashscanner/trashscanner_api/internal/models"
)

// newMockPredictor creates a new instance of mockPredictor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPredictor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPredictor {
	mock := &mockPredictor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPredictor is an autogenerated mock type for the predictor type
type mockPredictor struct {
	mock.Mock
}

type mockPredictor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPredictor) EXPECT() *mockPredictor_Expecter {
	return &mockPredictor_Expecter{mock: &_m.Mock}
}

// Predict provides a mock function for the type mockPredictor
func (_mock *mockPredictor) Predict(ctx context.Context, scanURL string) (*models.Prediction, error) {
	ret := _mock.Called(ctx, scanURL)

	if len(ret) == 0 {
		panic("no return value specified for Predict")
	}

	var r0 *models.Prediction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Prediction, error)); ok {
		return returnFunc(ctx, scanURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Prediction); ok {
		r0 = returnFunc(ctx, scanURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Prediction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, scanURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPredictor_Predict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Predict'
type mockPredictor_Predict_Call struct {
	*mock.Call
}

// Predict is a helper method to define mock.On call
//   - ctx context.Context
//   - scanURL string
func (_e *mockPredictor_Expecter) Predict(ctx interface{}, scanURL interface{}) *mockPredictor_Predict_Call {
	return &mockPredictor_Predict_Call{Call: _e.mock.On("Predict", ctx, scanURL)}
}

func (_c *mockPredictor_Predict_Call) Run(run func(ctx context.Context, scanURL string)) *mockPredictor_Predict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPredictor_Predict_Call) Return(prediction *models.Prediction, err error) *mockPredictor_Predict_Call {
	_c.Call.Return(prediction, err)
	return _c
}

func (_c *mockPredictor_Predict_Call) RunAndReturn(run func(ctx context.Context, scanURL string) (*models.Prediction, error)) *mockPredictor_Predict_Call {
	_c.Call.Return(run)
	return _c
}
