// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompletePrediction(ctx context.Context, arg CompletePredictionParams) error
	CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) (uuid.UUID, error)
	CreateNewPrediction(ctx context.Context, arg CreateNewPredictionParams) (Prediction, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateStats(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveTokensByUser(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	GetLoginHistoryByUser(ctx context.Context, arg GetLoginHistoryByUserParams) ([]LoginHistory, error)
	GetPrediction(ctx context.Context, id uuid.UUID) (Prediction, error)
	GetPredictionsByUserID(ctx context.Context, arg GetPredictionsByUserIDParams) ([]Prediction, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStatsByUserID(ctx context.Context, userID uuid.UUID) (Stat, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateStats(ctx context.Context, arg UpdateStatsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
