// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getStatsByUserID = `-- name: GetStatsByUserID :one
SELECT id, user_id, status, rating, files_scanned, total_weight, achievements, trash_by_types, last_scanned_at, created_at, updated_at FROM stats
WHERE user_id = $1
`

func (q *Queries) GetStatsByUserID(ctx context.Context, userID uuid.UUID) (Stat, error) {
	row := q.db.QueryRow(ctx, getStatsByUserID, userID)
	var i Stat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Rating,
		&i.FilesScanned,
		&i.TotalWeight,
		&i.Achievements,
		&i.TrashByTypes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStats = `-- name: UpdateStats :exec
UPDATE stats
SET
    status = $1,
    rating = $2,
    files_scanned = $3,
    total_weight = $4,
    achievements = $5,
    trash_by_types = $6,
    last_scanned_at = $7,
    updated_at = now()
WHERE id = $8
`

type UpdateStatsParams struct {
	Status        string             `json:"status"`
	Rating        int32              `json:"rating"`
	FilesScanned  int32              `json:"files_scanned"`
	TotalWeight   float64            `json:"total_weight"`
	Achievements  []byte             `json:"achievements"`
	TrashByTypes  []byte             `json:"trash_by_types"`
	LastScannedAt pgtype.Timestamptz `json:"last_scanned_at"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateStats(ctx context.Context, arg UpdateStatsParams) error {
	_, err := q.db.Exec(ctx, updateStats,
		arg.Status,
		arg.Rating,
		arg.FilesScanned,
		arg.TotalWeight,
		arg.Achievements,
		arg.TrashByTypes,
		arg.LastScannedAt,
		arg.ID,
	)
	return err
}
