// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/users": {
            "get": {
                "description": "Get paginated list of all users with their stats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get users list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUserListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user with specific role (e.g., admin)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create user as admin",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrConflict"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check server health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Is server healthy",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate user and return JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tokens for existing user",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/predictions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of predictions for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predictions"
                ],
                "summary": "Get a list of predictions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Prediction result",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.PredictionResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a new prediction for a user",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predictions"
                ],
                "summary": "Start a new prediction",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "scan",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Prediction result",
                        "schema": {
                            "$ref": "#/definitions/dto.PredictionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/predictions/{PredictionID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a prediction by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predictions"
                ],
                "summary": "Get a prediction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prediction ID UUID format",
                        "name": "PredictionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Prediction result",
                        "schema": {
                            "$ref": "#/definitions/dto.PredictionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "Resource not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Get new access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "201": {
                        "description": "New access token set in HttpOnly cookie"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired token",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Authenticate user and return JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered and tokens returned",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user details by ID (requires authentication)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user information",
                "responses": {
                    "200": {
                        "description": "User information",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete the authenticated user's account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user account",
                "responses": {
                    "204": {
                        "description": "User deleted successfully"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "description": "New user details",
                        "name": "updateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User information",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/users/me/avatar": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload and set a new avatar for the authenticated user",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Set user avatar",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Avatar image file (JPEG or PNG, max 10MB)",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Avatar updated successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadAvatarResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid avatar file",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove the avatar of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user avatar",
                "responses": {
                    "204": {
                        "description": "Avatar deleted successfully"
                    },
                    "400": {
                        "description": "No avatar to delete",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/users/me/change-password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change the password of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Change user password",
                "parameters": [
                    {
                        "description": "New password details",
                        "name": "changePasswordRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Password changed successfully"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        },
        "/users/me/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke all tokens for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Logout user",
                "responses": {
                    "204": {
                        "description": "User logged out successfully"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user ID mismatch",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrForbidden"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/errlocal.ErrInternal"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AdminUserListResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AdminUserResponse"
                    }
                }
            }
        },
        "dto.AdminUserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "last_login_at": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "stat": {
                    "$ref": "#/definitions/dto.StatResponse"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.AuthRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "login": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "dto.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "old_password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "dto.CreateAdminRequest": {
            "type": "object",
            "required": [
                "login",
                "name",
                "password",
                "role"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                }
            }
        },
        "dto.LoginUserRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "dto.PredictionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/models.PredictionResult"
                },
                "scan_key": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.PredictionStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.StatResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "files_scanned": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_scanned_at": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.UserStatus"
                },
                "total_weight": {
                    "type": "number"
                },
                "trash_by_types": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 3
                }
            }
        },
        "dto.UploadAvatarResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "http://localhost:9000/trashscanner-images/user-id/avatars/avatar.jpg"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_login_at": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "stat": {
                    "$ref": "#/definitions/models.Stat"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "errlocal.ErrBadRequest": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "errlocal.ErrConflict": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "errlocal.ErrForbidden": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "errlocal.ErrInternal": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "errlocal.ErrNotFound": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "errlocal.ErrUnauthorized": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "system": {
                    "type": "string"
                }
            }
        },
        "models.PredictionResult": {
            "type": "object",
            "additionalProperties": {
                "type": "number",
                "format": "float64"
            }
        },
        "models.PredictionStatus": {
            "type": "string",
            "enum": [
                "processing",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "PredictionProcessingStatus",
                "PredictionCompletedStatus",
                "PredictionFailedStatus"
            ]
        },
        "models.Role": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "anonymous"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleUser",
                "RoleAnonymous"
            ]
        },
        "models.Stat": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "files_scanned": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_scanned_at": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.UserStatus"
                },
                "total_weight": {
                    "type": "number"
                },
                "trash_by_types": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.UserStatus": {
            "type": "string",
            "enum": [
                "newbie",
                "eco_scout",
                "green_guard",
                "eco_warrior",
                "nature_hero",
                "earth_defender",
                "eco_champion",
                "planet_guardian",
                "eco_legend"
            ],
            "x-enum-comments": {
                "UserStatusEarthDefend": "Защитник Земли 1500+",
                "UserStatusEcoChampion": "Эко-чемпион 3000+",
                "UserStatusEcoLegend": "Эко-легенда 10000+",
                "UserStatusEcoScout": "Эко-разведчик 100+",
                "UserStatusEcoWarrior": "Эко-воин 500+",
                "UserStatusGreenGuard": "Зеленый страж 300+",
                "UserStatusNatureHero": "Герой природы 1000+",
                "UserStatusNewbie": "Новичок 0",
                "UserStatusPlanetGuard": "Хранитель планеты 5000+"
            },
            "x-enum-descriptions": [
                "Новичок 0",
                "Эко-разведчик 100+",
                "Зеленый страж 300+",
                "Эко-воин 500+",
                "Герой природы 1000+",
                "Защитник Земли 1500+",
                "Эко-чемпион 3000+",
                "Хранитель планеты 5000+",
                "Эко-легенда 10000+"
            ],
            "x-enum-varnames": [
                "UserStatusNewbie",
                "UserStatusEcoScout",
                "UserStatusGreenGuard",
                "UserStatusEcoWarrior",
                "UserStatusNatureHero",
                "UserStatusEarthDefend",
                "UserStatusEcoChampion",
                "UserStatusPlanetGuard",
                "UserStatusEcoLegend"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TrashScanner API",
	Description:      "This is a sample server TrashScanner API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
